-- seed.sql
-- Sample data for the research library database (Enerel's microservice).
-- Assumes init.sql has already been run. All data is for demo user_id = 1.

-- ---------------------------------------------------------------------------
-- documents: 8 documents spanning every doc_type, none pre-summarised and
-- none pre-embedded. Summaries and embeddings are generated by calling the
-- API (POST /api/documents/:id/summarize creates both; see embeddings.py) --
-- seeding them here would mean either baking in fake model output or making
-- the database build depend on a live Ollama container, and this build step
-- runs with neither.
-- ---------------------------------------------------------------------------
INSERT INTO documents
    (user_id, title, source, doc_type, published_on, body_text, created_at, updated_at)
VALUES
    (1,
     'Understanding Dollar-Cost Averaging',
     'Investopedia',
     'guide',
     '2025-11-03',
     'Dollar-cost averaging (DCA) is an investment strategy in which an investor divides the total amount to be invested across periodic purchases of a target asset, in an effort to reduce the impact of volatility on the overall purchase. The purchases occur regardless of the asset''s price and at regular intervals. In effect, this strategy removes much of the detailed work of attempting to time the market in order to make purchases of equities at the best prices. Dollar-cost averaging is also called the constant dollar plan. By investing a fixed dollar amount at each interval, an investor buys more shares when prices are low and fewer shares when prices are high, which can lower the average cost per share over time compared with a single lump-sum purchase made at an unfavourable moment. Critics note that, because markets tend to rise over the long run, a lump-sum investment made immediately typically outperforms DCA in expectation; the appeal of DCA is behavioural and risk-management, not a guarantee of higher returns. DCA is commonly used in employer retirement plans, where contributions are automatically deducted from every paycheck and invested on a set schedule, and by individual investors who prefer a disciplined, automated approach over trying to pick entry points.',
     '2026-01-05 09:00:00', '2026-01-05 09:00:00'),

    (1,
     'RBA Holds Cash Rate at 4.35% Amid Cooling Inflation',
     'Australian Financial Review',
     'news',
     '2026-02-04',
     'The Reserve Bank of Australia left the cash rate unchanged at 4.35% at its February meeting, citing signs that inflation is gradually returning to the 2-3% target band without further tightening. Governor comments pointed to softer services inflation and a labour market that has cooled without a sharp rise in unemployment, which the board characterised as consistent with a soft landing. Markets had priced a small chance of a cut, so the hold was broadly in line with expectations. Economists at the major banks were split on the timing of the first cut, with forecasts ranging from mid-year to early next year depending on how quickly trimmed-mean inflation continues to fall. The Australian dollar was little changed against the US dollar following the announcement. The board reiterated that policy would remain data-dependent and that it was not ruling anything in or out, language it has used consistently since inflation peaked. Mortgage holders on variable rates were left facing another month of unchanged repayments, while savers continued to benefit from term deposit rates near decade highs.',
     '2026-02-05 08:30:00', '2026-02-05 08:30:00'),

    (1,
     'Annual Report FY2025 -- Commonwealth Bank of Australia (Extract)',
     'CBA Investor Relations',
     'report',
     '2025-08-14',
     'Commonwealth Bank of Australia reported cash net profit after tax of $10.2 billion for the financial year ended 30 June 2025, broadly flat on the prior year. Net interest margin held at 2.07%, supported by disciplined deposit pricing that offset continued competition in home lending. The bank''s common equity tier 1 capital ratio finished the year at 12.3%, well above regulatory minimums, and the board declared a final dividend of $2.50 per share, taking the full-year dividend to $4.65 per share, fully franked. Home lending grew at broadly system pace, while business lending outpaced the market, particularly in the bank''s core small business segment. Credit quality remained sound, with loan impairment expense as a proportion of average gross loans and acceptances staying below the long-run average, though the bank flagged a modest increase in early-stage arrears among mortgage customers as evidence of cost-of-living pressure. Management reaffirmed its strategy of investing in technology and digital banking while targeting continued cost discipline, with the cost-to-income ratio ending the year at 45.3%.',
     '2025-08-20 10:00:00', '2025-08-20 10:00:00'),

    (1,
     'A Beginner''s Guide to Exchange-Traded Funds (ETFs)',
     'Vanguard Investor Education',
     'guide',
     '2025-09-10',
     'An exchange-traded fund, or ETF, is a basket of securities that trades on an exchange the same way an individual stock does. ETFs can hold assets such as stocks, bonds or commodities, and most track an underlying index, aiming to replicate its performance before fees. Because they trade throughout the day at market-determined prices, ETFs differ from traditional managed funds, which are only priced once daily after the market closes. Popular reasons investors choose ETFs include low management costs compared with actively managed funds, instant diversification across many underlying holdings in a single trade, and transparency, since most ETF providers publish their full holdings daily. Risks include tracking error, where the fund''s return diverges slightly from its index, and the fact that an ETF is only as diversified as the index it follows -- a narrow sector ETF carries concentration risk just as a single stock does. New investors are generally encouraged to start with broad, low-cost index ETFs covering an entire market before considering more specialised products.',
     '2025-09-15 14:20:00', '2025-09-15 14:20:00'),

    (1,
     'Global Equity Markets Outlook -- Q1 2026',
     'Morningstar Research',
     'research_note',
     '2026-01-20',
     'Global equity valuations enter 2026 above their 10-year average on a forward price-to-earnings basis, driven largely by continued strength in US large-cap technology names. Analysts remain divided on whether elevated valuations are justified by structurally higher earnings growth from productivity gains, or whether markets are pricing in an overly optimistic path for interest rate cuts. Outside the US, valuations in developed international markets and emerging markets remain closer to historical norms, which some strategists argue offers a more attractive risk-reward setup for diversified investors. Key risks flagged for the quarter include a resurgence in energy prices affecting the inflation outlook, geopolitical tensions affecting supply chains, and the possibility that central banks hold rates higher for longer than currently priced by futures markets. The note recommends investors maintain diversification across regions and market capitalisations rather than concentrating further in the recent winners, while acknowledging that momentum has rewarded concentration for several years running.',
     '2026-01-22 11:15:00', '2026-01-22 11:15:00'),

    (1,
     'ASIC Regulatory Guide -- Managed Investment Schemes (Summary)',
     'Australian Securities and Investments Commission',
     'filing',
     '2024-05-01',
     'This guide summarises the obligations of a responsible entity operating a registered managed investment scheme under the Corporations Act. A responsible entity must hold an Australian financial services licence authorising it to operate the scheme, act in the best interests of members, and treat members who hold interests of the same class equally. Schemes must be registered with ASIC before interests in the scheme are offered to retail investors, and a product disclosure statement must be given to retail clients before they invest. The guide sets out expectations around compliance plans, which must describe the measures the responsible entity will apply to ensure compliance with the scheme''s constitution and the Corporations Act, and around the role of the compliance committee where the responsible entity''s board does not have a majority of external directors. It also addresses related-party transactions, valuation practices for scheme property, and the circumstances in which a scheme may be wound up. The guide is intended for responsible entities, their advisers, and compliance staff, and does not itself constitute legal advice.',
     '2024-06-01 09:00:00', '2024-06-01 09:00:00'),

    (1,
     'The Case for a Barbell Fixed-Income Strategy in a Higher-Rate World',
     'BlackRock Whitepaper Series',
     'whitepaper',
     '2025-12-02',
     'A barbell fixed-income strategy combines short-duration bonds, which are less sensitive to interest rate moves and provide liquidity and income, with long-duration bonds, which offer greater price appreciation potential if rates fall, while deliberately underweighting intermediate maturities. In a higher-for-longer rate environment, this paper argues the approach lets investors capture attractive yields at the short end without giving up convexity at the long end should central banks eventually ease policy more aggressively than currently expected. The paper walks through historical periods of rate volatility and shows that a barbell allocation tended to outperform a pure bullet strategy concentrated in intermediate maturities during regime shifts, though it underperformed a laddered approach during periods of gradual, well-telegraphed rate changes. The authors caution that the strategy requires more active rebalancing than a simple buy-and-hold bond ladder, and that transaction costs and reinvestment risk at the short end should be weighed against the theoretical benefits before adopting it. The paper does not recommend specific securities and presents the strategy as one input among several for a fixed-income allocation decision.',
     '2025-12-05 16:45:00', '2025-12-05 16:45:00'),

    (1,
     'Five Common Behavioural Biases That Hurt Investment Returns',
     'CFA Institute Blog',
     'article',
     '2026-03-11',
     'Loss aversion describes the tendency to feel the pain of a loss roughly twice as intensely as the pleasure of an equivalent gain, which can lead investors to hold losing positions too long in the hope of breaking even, and to sell winning positions too early to lock in gains. Confirmation bias leads investors to seek out information that supports a position they already hold while discounting evidence to the contrary, reinforcing conviction rather than testing it. Recency bias causes investors to overweight recent events -- extrapolating a recent bull run indefinitely into the future, or becoming overly conservative immediately after a downturn. Herding describes the tendency to follow the crowd into popular trades, which can amplify bubbles and crashes as more investors pile in near the top and exit near the bottom. Overconfidence leads investors to trade more frequently and take on more concentrated risk than their actual skill or information advantage would justify, a pattern that research has repeatedly linked to lower net-of-fees returns. The article suggests that a written investment plan, agreed in advance and revisited only on a schedule rather than in reaction to daily price moves, is one of the more effective defences against all five biases.',
     '2026-03-12 07:50:00', '2026-03-12 07:50:00');
